version: '3.4'

services:
  db:
    image: "microsoft/mssql-server-linux"
    build:
      context: .
      dockerfile: infra/mssql/Dockerfile     
    environment:
      SA_PASSWORD: "BonjourMadame69"
      ACCEPT_EULA: "Y"
    ports:
      - target: 1433
        published: 1433
  redis:
    build:
      context: infra/redis/
      dockerfile: Dockerfile     
    ports:
      - target: 6379
        published: 6379

