// <auto-generated />
using System;
using Data.Model.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(TunderDbContext))]
    [Migration("20181024234519_Match")]
    partial class Match
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Model.MatchAction", b =>
                {
                    b.Property<long>("LikerID");

                    b.Property<long>("LikedID");

                    b.HasKey("LikerID", "LikedID");

                    b.HasIndex("LikedID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Data.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivationToken");

                    b.Property<string>("AuthToken");

                    b.Property<DateTime>("BirthDateTime");

                    b.Property<string>("Email");

                    b.Property<Guid>("Guid");

                    b.Property<byte[]>("HashedPassword");

                    b.Property<string>("Name");

                    b.Property<byte[]>("Salt");

                    b.Property<int>("Sex");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.Model.MatchAction", b =>
                {
                    b.HasOne("Data.Model.User", "Liked")
                        .WithMany("MatchActionsFrom")
                        .HasForeignKey("LikedID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Data.Model.User", "Liker")
                        .WithMany("MatchActionsTo")
                        .HasForeignKey("LikerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
